# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ArcadiaAssistant' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ArcadiaAssistant
  pod 'AppCenter/Push', '~> 1.11.0'
  pod 'AppCenter/Crashes', '~> 1.11.0'
  pod 'AppCenter/Analytics', '~> 1.11.0'
  pod 'AppCenterReactNativeShared', '~> 1.10.0'

  target 'ArcadiaAssistantTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
