platform :ios, '10.0'

target 'ArcadiaAssistant' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ArcadiaAssistant
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.1'

  target 'ArcadiaAssistantTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
