FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY . ./
RUN dotnet publish Arcadia.Assistant.Server.Console/Arcadia.Assistant.Server.Console.csproj -c Release -o out

FROM microsoft/dotnet:2.1-aspnetcore-runtime
WORKDIR /app
EXPOSE 80 63301
COPY --from=build-env /app/Arcadia.Assistant.Server.Console/out .
ENTRYPOINT ["dotnet", "Arcadia.Assistant.Server.Console.dll"]