version: '3.4'

services:
  arcadia.assistant.web:
    image: arcadia.assistant.web
    build:
      context: ./
      dockerfile: Dockerfile.web
    ports:
      - "63601:80"
      - "63302:63302"

    environment:
      - SERVER:HOST = arcadia.assistant.server.console
      - SERVER:PORT = 63301

  arcadia.assistant.server.console:
    image: arcadia.assistant.server.console
    build:
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - "63301:63301"